In [10]:
import jax.numpy as jnp

def conditional_distribution(joint_mean, joint_covariance, x, dimensions):
    y_dimensions = [i for i in range(len(joint_mean)) if i not in dimensions]
    
    dimensions = jnp.array(dimensions)
    y_dimensions = jnp.array(y_dimensions)

    mean_x = jnp.take(joint_mean, dimensions)
    mean_y = jnp.take(joint_mean, y_dimensions)
    
    # Create a grid of indices from A and B using meshgrid
    cov_XX = joint_covariance[jnp.ix_(dimensions, dimensions)]
    cov_YY = joint_covariance[jnp.ix_(y_dimensions, y_dimensions)]
    cov_YX = joint_covariance[jnp.ix_(y_dimensions, dimensions)]
    cov_XY = joint_covariance[jnp.ix_(dimensions, y_dimensions)]
    
    mean_y_given_x = mean_y + cov_YX @ jnp.linalg.inv(cov_XX) @ (x - mean_x)

    cov_y_given_x = cov_YY - cov_YX @ jnp.linalg.inv(cov_XX) @ cov_XY

    return mean_y_given_x, cov_y_given_x

XY_mean = jnp.array([1000., 0.1, 5.2, 400., 0.7,
                      0.3, 3.0, 0.25, -0.1, 0.5,
                      1500, 0.08, 6.1, 0.8, 0.3,
                      3.0, 0.2, -0.1, 0.5])
XY_sigma = jnp.diag(jnp.array([1.0 ** 2, 0.02 ** 2, 1.0 ** 2, 200 ** 2, 0.1 ** 2,
                                0.1 ** 2, 0.5 ** 2, 0.1 ** 2, 0.02 ** 2, 0.2 ** 2,
                                1.0 ** 2, 0.02 ** 2, 1.0 ** 2, 0.1 ** 2, 0.05 ** 2,
                                1.0 ** 2, 0.05 ** 2, 0.02 ** 2, 0.2 ** 2]))
XY_sigma = XY_sigma.at[4, 6].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[6, 6]))
XY_sigma = XY_sigma.at[6, 4].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[6, 6]))
XY_sigma = XY_sigma.at[4, 13].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[13, 13]))
XY_sigma = XY_sigma.at[13, 4].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[13, 13]))
XY_sigma = XY_sigma.at[4, 15].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[15, 15]))
XY_sigma = XY_sigma.at[15, 4].set(0.6 * jnp.sqrt(XY_sigma[4, 4]) * jnp.sqrt(XY_sigma[15, 15]))
XY_sigma = XY_sigma.at[6, 13].set(0.6 * jnp.sqrt(XY_sigma[6, 6]) * jnp.sqrt(XY_sigma[13, 13]))
XY_sigma = XY_sigma.at[13, 6].set(0.6 * jnp.sqrt(XY_sigma[6, 6]) * jnp.sqrt(XY_sigma[13, 13]))
XY_sigma = XY_sigma.at[6, 15].set(0.6 * jnp.sqrt(XY_sigma[6, 6]) * jnp.sqrt(XY_sigma[15, 15]))
XY_sigma = XY_sigma.at[15, 6].set(0.6 * jnp.sqrt(XY_sigma[6, 6]) * jnp.sqrt(XY_sigma[15, 15]))
XY_sigma = XY_sigma.at[13, 15].set(0.6 * jnp.sqrt(XY_sigma[13, 13]) * jnp.sqrt(XY_sigma[15, 15]))
XY_sigma = XY_sigma.at[15, 13].set(0.6 * jnp.sqrt(XY_sigma[13, 13]) * jnp.sqrt(XY_sigma[15, 15]))

x = jnp.array([0.5, 0.5])  # Example value of X
dimensions = [4, 13]  # Indices for dimensions 5 and 14 (zero-indexed)

mean_y_given_x, cov_y_given_x = conditional_distribution(XY_mean, XY_sigma, x, dimensions)


In [4]:
joint_covariance = XY_sigma
joint_mean = XY_mean

y_dimensions = [i for i in range(len(joint_mean)) if i not in dimensions]

dimensions = jnp.array(dimensions)
y_dimensions = jnp.array(y_dimensions)

mean_x = jnp.take(joint_mean, dimensions)
mean_y = jnp.take(joint_mean, y_dimensions)

# Create a grid of indices from A and B using meshgrid
cov_XX = joint_covariance[jnp.ix_(dimensions, dimensions)]
cov_YY = joint_covariance[jnp.ix_(y_dimensions, y_dimensions)]
cov_YX = joint_covariance[jnp.ix_(y_dimensions, dimensions)]
cov_XY = joint_covariance[jnp.ix_(dimensions, y_dimensions)]

mean_y_given_x = mean_y + cov_YX @ jnp.linalg.inv(cov_XX) @ (x - mean_x)
cov_y_given_x = cov_YY - cov_YX @ jnp.linalg.inv(cov_XX) @ cov_XY


In [9]:
cov_y_given_x


Array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 3.9999999e-04, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 4.0000000e+04,
        0.0000000e+00, 0.0000000e+00, 0.0000

In [8]:
cov_YY

Array([[1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 4.0e-04, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 4.0e+04, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 1.0e-02, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 0.0e+00, 2.5e-01, 0.0e+00,
        0.0e+00, 0.0e+00, 0.0e+00, 0.0e

In [7]:
jnp.linalg.inv(cov_XX)

Array([[156.25003, -93.75002],
       [-93.75003, 156.25003]], dtype=float32)

In [6]:
cov_YX @ jnp.linalg.inv(cov_XX) @ cov_XY

Array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.      

In [5]:
cov_XX

Array([[0.01 , 0.006],
       [0.006, 0.01 ]], dtype=float32)

In [19]:
jnp.diag(cov_YX @ jnp.linalg.inv(cov_XX) @ cov_XY)

Array([0.       , 0.       , 0.       , 0.       , 0.       , 1.0285715,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.0285715, 0.       , 0.       , 0.       ],      dtype=float32)

In [20]:
jnp.diag(cov_YY)

Array([1.e+00, 2.e-02, 1.e+00, 2.e+02, 1.e-01, 5.e-01, 1.e-01, 2.e-02,
       2.e-01, 1.e+00, 2.e-02, 1.e+00, 5.e-02, 1.e+00, 5.e-02, 2.e-02,
       2.e-01], dtype=float32)

In [5]:
jnp.diag(cov_y_given_x)

Array([ 1.0000000e+00,  2.0000000e-02,  1.0000000e+00,  2.0000000e+02,
        1.0000000e-01, -5.2857149e-01,  1.0000000e-01,  2.0000000e-02,
        2.0000000e-01,  1.0000000e+00,  2.0000000e-02,  1.0000000e+00,
        5.0000001e-02, -2.8571486e-02,  5.0000001e-02,  2.0000000e-02,
        2.0000000e-01], dtype=float32)

In [31]:
mean_y_given_x.shape

(17,)

In [23]:
jnp.ix_(jnp.array([4, 13]), jnp.array([4, 13]))

(Array([[ 4],
        [13]], dtype=int32),
 Array([[ 4, 13]], dtype=int32))

In [21]:
np.ix_(dimensions, dimensions)

(array([[ 4],
        [13]]),
 array([[ 4, 13]]))

In [19]:
A = jnp.array([1, 2, 3, 4, 5])

# List of indices
l = jnp.array([0, 2, 4])

# Extract elements using jnp.take()
result = jnp.take(A, l)
print(result)

[1 3 5]


In [24]:
import jax.numpy as jnp

# Create one-dimensional arrays A and B representing indices
A = jnp.array([0, 1])
B = jnp.array([2, 3])

# Create a 2D array C
C = jnp.array([[1, 2, 3, 4],
               [5, 6, 7, 8]])

# Create a grid of indices from A and B using meshgrid
A_grid, B_grid = jnp.meshgrid(A, B, indexing='ij')

# Convert the grid of indices into a flat index array
flat_indices = jnp.ravel_multi_index((A_grid, B_grid), C.shape)

# Extract elements from C using the flat index array
result = jnp.take(C, flat_indices)

print(result)


[[3 4]
 [7 8]]
